### ISSUE TITLE
Auto reload

### ISSUE THREAD

**Issue by biplovdahal** [nicholaskajoh/React-Django#1]
How would I auto reload? It seems like I can't update my component after I save it. also says .service_worker is not found.

**Comment by nicholaskajoh** [comment]
Auto reload works out of the box with Create React App if you run the app with `npm start` (or `yarn start`. For the service worker error you're experiencing, I'll need more info to be able to help, but it's out of the scope of this repo/project.

**Comment by nicholaskajoh** [comment]
Auto reload works out of the box with Create React App if you run the app with `npm start` (or `yarn start`). For the service worker error you're experiencing, I'll need more info to be able to help, but it's out of the scope of this repo/project.
